; super game boy palettes
PAL_ROUTE     EQU $00
PAL_PALLET    EQU $01
PAL_VIRIDIAN  EQU $02
PAL_PEWTER    EQU $03
PAL_CERULEAN  EQU $04
PAL_LAVENDER  EQU $05
PAL_VERMILION EQU $06
PAL_CELADON   EQU $07
PAL_FUCHSIA   EQU $08
PAL_CINNABAR  EQU $09
PAL_INDIGO    EQU $0A
PAL_SAFFRON   EQU $0B
PAL_TOWNMAP   EQU $0C
PAL_LOGO1     EQU $0D
PAL_LOGO2     EQU $0E
;PAL_0F       EQU $0F
PAL_MEWMON    EQU $10
PAL_BLUEMON   EQU $11
PAL_REDMON    EQU $12
PAL_CYANMON   EQU $13
PAL_PURPLEMON EQU $14
PAL_BROWNMON  EQU $15
PAL_GREENMON  EQU $16
PAL_PINKMON   EQU $17
PAL_YELLOWMON EQU $18
PAL_GREYMON   EQU $19
PAL_SLOTS1    EQU $1A
PAL_SLOTS2    EQU $1B
PAL_SLOTS3    EQU $1C
PAL_SLOTS4    EQU $1D
PAL_BLACK     EQU $1E
PAL_GREENBAR  EQU $1F
PAL_YELLOWBAR EQU $20
PAL_REDBAR    EQU $21
PAL_BADGE     EQU $22
PAL_CAVE      EQU $23
PAL_GAMEFREAK EQU $24
PAL_BULBASAUR  EQU $25
PAL_IVYSAUR    EQU $26
PAL_VENUSAUR   EQU $27
PAL_CHARMANDER EQU $28
PAL_CHARMELEON EQU $29
PAL_CHARIZARD  EQU $2A
PAL_SQUIRTLE   EQU $2B ; X
PAL_WARTORTLE  EQU $2B ; X
PAL_BLASTOISE  EQU $2C
PAL_CATERPIE   EQU $2D
PAL_METAPOD    EQU $2E
PAL_BUTTERFREE EQU $2F
PAL_WEEDLE     EQU $30
PAL_KAKUNA     EQU $31
PAL_BEEDRILL   EQU $32
PAL_PIDGEY     EQU $33
PAL_PIDGEOTTO  EQU $34 ; X
PAL_PIDGEOT    EQU $34 ; X
PAL_RATTATA    EQU $35
PAL_RATICATE   EQU $36
PAL_SPEAROW    EQU $37
PAL_FEAROW     EQU $38
PAL_EKANS      EQU $39
PAL_ARBOK      EQU $3A
PAL_PIKACHU    EQU $3B ; X
PAL_RAICHU     EQU $3C
PAL_SANDSHREW  EQU $3D
PAL_SANDSLASH  EQU $3E
PAL_NIDORAN_F  EQU $3F
PAL_NIDORINA   EQU $40
PAL_NIDOQUEEN  EQU $41
PAL_NIDORAN_M  EQU $42
PAL_NIDORINO   EQU $43
PAL_NIDOKING   EQU $44
PAL_CLEFAIRY   EQU $45 ; X
PAL_CLEFABLE   EQU $45 ; X
PAL_VULPIX     EQU $46
PAL_NINETALES  EQU $47
PAL_JIGGLYPUFF EQU $48 ; X
PAL_WIGGLYTUFF EQU $48 ; X
PAL_ZUBAT      EQU $49 ; X
PAL_GOLBAT     EQU $49 ; X
PAL_ODDISH     EQU $4A
PAL_GLOOM      EQU $4B
PAL_VILEPLUME  EQU $4C
PAL_PARAS      EQU $4D
PAL_PARASECT   EQU $4E
PAL_VENONAT    EQU $4F
PAL_VENOMOTH   EQU $50
PAL_DIGLETT    EQU $51 ; X
PAL_DUGTRIO    EQU $51 ; X
PAL_MEOWTH     EQU $52
PAL_PERSIAN    EQU $53
PAL_PSYDUCK    EQU $54
PAL_GOLDUCK    EQU $55
PAL_MANKEY     EQU $56
PAL_PRIMEAPE   EQU $57
PAL_GROWLITHE  EQU $58 ; X
PAL_ARCANINE   EQU $58 ; X
PAL_POLIWAG    EQU $59
PAL_POLIWHIRL  EQU $5A
PAL_POLIWRATH  EQU $5B
PAL_ABRA       EQU $5C ; X
PAL_KADABRA    EQU $5C ; X
PAL_ALAKAZAM   EQU $5C ; X
PAL_MACHOP     EQU $5D
PAL_MACHOKE    EQU $5E
PAL_MACHAMP    EQU $5F
PAL_BELLSPROUT EQU $60
PAL_WEEPINBELL EQU $61
PAL_VICTREEBEL EQU $62
PAL_TENTACOOL  EQU $63
PAL_TENTACRUEL EQU $64
PAL_GEODUDE    EQU $65 ; X
PAL_GRAVELER   EQU $66
PAL_GOLEM      EQU $65 ; X
PAL_PONYTA     EQU $67 ; X
PAL_RAPIDASH   EQU $67 ; X
PAL_SLOWPOKE   EQU $68
PAL_SLOWBRO    EQU $69
PAL_MAGNEMITE  EQU $6A ; X
PAL_MAGNETON   EQU $6A ; X
PAL_FARFETCH_D EQU $6B
PAL_DODUO      EQU $6C
PAL_DODRIO     EQU $6D
PAL_SEEL       EQU $6E
PAL_DEWGONG    EQU $6F
PAL_GRIMER     EQU $70 ; X
PAL_MUK        EQU $70 ; X
PAL_SHELLDER   EQU $71
PAL_CLOYSTER   EQU $72
PAL_GASTLY     EQU $73
PAL_HAUNTER    EQU $74
PAL_GENGAR     EQU $75
PAL_ONIX       EQU $76
PAL_DROWZEE    EQU $77
PAL_HYPNO      EQU $78
PAL_KRABBY     EQU $79 ; X
PAL_KINGLER    EQU $79 ; X
PAL_VOLTORB    EQU $7A ; X
PAL_ELECTRODE  EQU $7A ; X
PAL_EXEGGCUTE  EQU $7B
PAL_EXEGGUTOR  EQU $7C
PAL_CUBONE     EQU $7D ; X
PAL_MAROWAK    EQU $7D ; X
PAL_HITMONLEE  EQU $7E
PAL_HITMONCHAN EQU $7F
PAL_LICKITUNG  EQU $80
PAL_KOFFING    EQU $81 ; X
PAL_WEEZING    EQU $81 ; X
PAL_RHYHORN    EQU $82 ; X
PAL_RHYDON     EQU $82 ; X
PAL_CHANSEY    EQU $83
PAL_TANGELA    EQU $84
PAL_KANGASKHAN EQU $85
PAL_HORSEA     EQU $86
PAL_SEADRA     EQU $87
PAL_GOLDEEN    EQU $88
PAL_SEAKING    EQU $89
PAL_STARYU     EQU $8A
PAL_STARMIE    EQU $8B
PAL_MR_MIME    EQU $8C
PAL_SCYTHER    EQU $8D
PAL_JYNX       EQU $8E
PAL_ELECTABUZZ EQU $8F ; X
PAL_MAGMAR     EQU $90 ; X
PAL_PINSIR     EQU $91
PAL_TAUROS     EQU $92
PAL_MAGIKARP   EQU $93
PAL_GYARADOS   EQU $94
PAL_LAPRAS     EQU $95
PAL_DITTO      EQU $96
PAL_EEVEE      EQU $97
PAL_VAPOREON   EQU $98
PAL_JOLTEON    EQU $99
PAL_FLAREON    EQU $9A
PAL_PORYGON    EQU $9B
PAL_OMANYTE    EQU $9C ; X
PAL_OMASTAR    EQU $9C ; X
PAL_KABUTO     EQU $9D ; X
PAL_KABUTOPS   EQU $9D ; X
PAL_AERODACTYL EQU $9E
PAL_SNORLAX    EQU $9F
PAL_ARTICUNO   EQU $A0
PAL_ZAPDOS     EQU $A1
PAL_MOLTRES    EQU $A2
PAL_DRATINI    EQU $A3
PAL_DRAGONAIR  EQU $A4
PAL_DRAGONITE  EQU $A5
PAL_MEWTWO     EQU $A6
PAL_MEW        EQU $A7
PAL_PICHU      EQU $3B ; X
PAL_CLEFFA     EQU $A8
PAL_IGGLYBUFF  EQU $A9
PAL_CROBAT     EQU $AA
PAL_BELLOSSOM  EQU $AB
PAL_POLITOED   EQU $AC
PAL_SLOWKING   EQU $AD
PAL_MAGNEZONE  EQU $AE
PAL_STEELIX    EQU $AF
PAL_TYROGUE    EQU $B0
PAL_HITMONTOP  EQU $B1
PAL_LICKILICKY EQU $B2
PAL_RHYPERIOR  EQU $B3
PAL_HAPPINY    EQU $B4
PAL_BLISSEY    EQU $B5
PAL_TANGROWTH  EQU $B6
PAL_KINGDRA    EQU $B7
PAL_MIME_JR    EQU $B8
PAL_SCIZOR     EQU $B9
PAL_SMOOCHUM   EQU $BA
PAL_ELEKID     EQU $BB
PAL_ELECTIVIRE EQU $8F ; X
PAL_MAGBY      EQU $BC
PAL_MAGMORTAR  EQU $90 ; X
PAL_ESPEON     EQU $BD
PAL_UMBREON    EQU $BE
PAL_LEAFEON    EQU $BF
PAL_GLACEON    EQU $C0
PAL_PORYGON2   EQU $C1
PAL_PORYGON_Z  EQU $C2
PAL_MUNCHLAX   EQU $C3
PAL_YOUNGSTER     EQU $C4
PAL_BUGCATCHER    EQU $C5
PAL_LASS          EQU $C6
PAL_SAILOR        EQU $C7
PAL_JR_TRAINER_M  EQU $C8
PAL_JR_TRAINER_F  EQU $C9
PAL_POKEMANIAC    EQU $CA
PAL_SUPERNERD     EQU $CB
PAL_HIKER         EQU $CC
PAL_BIKER         EQU $CD
PAL_BURGLAR       EQU $CE
PAL_ENGINEER      EQU $CF
PAL_JUGGLER       EQU $D0
PAL_FISHERMAN     EQU $D1
PAL_SWIMMER       EQU $D2
PAL_CUEBALL       EQU $D3
PAL_GAMBLER       EQU $D4
PAL_BEAUTY        EQU $D5
PAL_PSYCHIC       EQU $D6
PAL_ROCKER        EQU $D7
PAL_JUGGLER2      EQU $D8
PAL_TAMER         EQU $D9
PAL_BIRDKEEPER    EQU $DA
PAL_BLACKBELT     EQU $DB
PAL_GARY1         EQU $DC ; X
PAL_OAK           EQU $DD
PAL_CHIEF         EQU $DE
PAL_SCIENTIST     EQU $DF
PAL_GIOVANNI      EQU $E0
PAL_ROCKET        EQU $E1
PAL_COOLTRAINER_M EQU $E2
PAL_COOLTRAINER_F EQU $E3
PAL_BRUNO         EQU $E4
PAL_BROCK         EQU $E5
PAL_MISTY         EQU $E6
PAL_LT_SURGE      EQU $E7
PAL_ERIKA         EQU $E8
PAL_KOGA          EQU $E9
PAL_BLAINE        EQU $EA
PAL_SABRINA       EQU $EB
PAL_GENTLEMAN     EQU $EC
PAL_GARY2         EQU $DC ; X
PAL_GARY3         EQU $DC ; X
PAL_LORELEI       EQU $ED
PAL_CHANNELER     EQU $EE
PAL_AGATHA        EQU $EF
PAL_LANCE         EQU $F0
PAL_HERO          EQU $F1
PAL_IVYSAURB      EQU $F2
PAL_VENUSAURB     EQU $F3
PAL_BLACK2        EQU $F4
PAL_PARTYMENU     EQU $F5
