MoveNames: ; b0000 (2c:4000)
	db "Pound@"
	db "Karate Chop@"
	db "DoubleSlap@"
	db "Comet Punch@"
	db "Mega Punch@"
	db "Pay Day@"
	db "Fire Punch@"
	db "Ice Punch@"
	db "ThunderPunch@"
	db "Scratch@"
	db "ViceGrip@"
	db "Guillotine@"
	db "Razor Wind@"
	db "Swords Dance@"
	db "Cut@"
	db "Gust@"
	db "Wing Attack@"
	db "Whirlwind@"
	db "Fly@"
	db "Bind@"
	db "Slam@"
	db "Vine Whip@"
	db "Stomp@"
	db "Double Kick@"
	db "Mega Kick@"
	db "Jump Kick@"
	db "Rolling Kick@"
	db "Sand-Attack@"
	db "Headbutt@"
	db "Horn Attack@"
	db "Fury Attack@"
	db "Horn Drill@"
	db "Tackle@"
	db "Body Slam@"
	db "Wrap@"
	db "Take Down@"
	db "Thrash@"
	db "Double-Edge@"
	db "Tail Whip@"
	db "Poison Sting@"
	db "Twineedle@"
	db "Pin Missile@"
	db "Leer@"
	db "Bite@"
	db "Growl@"
	db "Roar@"
	db "Sing@"
	db "Supersonic@"
	db "Sonicboom@"
	db "Disable@"
	db "Acid@"
	db "Ember@"
	db "Flamethrower@"
	db "Mist@"
	db "Water Gun@"
	db "Hydro Pump@"
	db "Surf@"
	db "Ice Beam@"
	db "Blizzard@"
	db "PsyBeam@"
	db "BubbleBeam@"
	db "Aurora Beam@"
	db "Hyper Beam@"
	db "Peck@"
	db "Drill Peck@"
	db "Submission@"
	db "Low Kick@"
	db "Counter@"
	db "Seismic Toss@"
	db "Strength@"
	db "Absorb@"
	db "Mega Drain@"
	db "Leech Seed@"
	db "Growth@"
	db "Razor Leaf@"
	db "SolarBeam@"
	db "PoisonPowder@"
	db "Stun Spore@"
	db "Sleep Powder@"
	db "Petal Dance@"
	db "String Shot@"
	db "Dragon Rage@"
	db "Fire Spin@"
	db "ThunderShock@"
	db "ThunderBolt@"
	db "Thunder Wave@"
	db "Thunder@"
	db "Rock Throw@"
	db "Earthquake@"
	db "Fissure@"
	db "Dig@"
	db "Toxic@"
	db "Confusion@"
	db "Psychic@"
	db "Hypnosis@"
	db "Meditate@"
	db "Agility@"
	db "Quick Attack@"
	db "Rage@"
	db "Teleport@"
	db "Night Shade@"
	db "Mimic@"
	db "Screech@"
	db "Double Team@"
	db "Recover@"
	db "Harden@"
	db "Minimize@"
	db "SmokeScreen@"
	db "Confuse Ray@"
	db "Withdraw@"
	db "Defense Curl@"
	db "Barrier@"
	db "Light Screen@"
	db "Haze@"
	db "Reflect@"
	db "Focus Energy@"
	db "Bide@"
	db "Metronome@"
	db "Mirror Move@"
	db "Selfdestruct@"
	db "Egg Bomb@"
	db "Lick@"
	db "Smog@"
	db "Sludge@"
	db "Bone Club@"
	db "Fire Blast@"
	db "Waterfall@"
	db "Clamp@"
	db "Swift@"
	db "Skull Bash@"
	db "Spike Cannon@"
	db "Constrict@"
	db "Amnesia@"
	db "Kinesis@"
	db "Softboiled@"
	db "Hi Jump Kick@"
	db "Glare@"
	db "Dream Eater@"
	db "Poison Gas@"
	db "Barrage@"
	db "Leech Life@"
	db "Lovely Kiss@"
	db "Sky Attack@"
	db "Transform@"
	db "Bubble@"
	db "Dizzy Punch@"
	db "Spore@"
	db "Flash@"
	db "Psywave@"
	db "Splash@"
	db "Acid Armor@"
	db "CrabHammer@"
	db "Explosion@"
	db "Fury Swipes@"
	db "Bonemerang@"
	db "Rest@"
	db "Rock Slide@"
	db "Hyper Fang@"
	db "Sharpen@"
	db "Conversion@"
	db "Tri Attack@"
	db "Super Fang@"
	db "Slash@"
	db "Substitute@"
	db "Struggle@"

