TrainerNames: ; 399ff (e:59ff)
	db "Youngster@"
	db "Bug Catcher@"
	db "Lass@"
	db "Sailor@"
	db "Jr.Trainer♂@"
	db "Jr.Trainer♀@"
	db "Pokémaniac@"
	db "Super Nerd@"
	db "Hiker@"
	db "Biker@"
	db "Burglar@"
	db "Engineer@"
	db "Juggler@"
	db "Fisherman@"
	db "Swimmer@"
	db "Cue Ball@"
	db "Gambler@"
	db "Beauty@"
	db "Psychic@"
	db "Rocker@"
	db "Juggler@"
	db "Tamer@"
	db "Bird Keeper@"
	db "Blackbelt@"
	db "Rival1@"
	db "Prof.Oak@"
	db "Chief@"
	db "Scientist@"
	db "Giovanni@"
	db "Rocket@"
	db "CoolTrainer♂@"
	db "CoolTrainer♀@"
	db "Bruno@"
	db "Brock@"
	db "Misty@"
	db "Lt.Surge@"
	db "Erika@"
	db "Koga@"
	db "Blaine@"
	db "Sabrina@"
	db "Gentleman@"
	db "Rival2@"
	db "Rival3@"
	db "Lorelei@"
	db "Channeler@"
	db "Agatha@"
	db "Lance@"
